name: Button
on:
  workflow_dispatch:
  
jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const expireMillis = 1000 * 60 * 60 * 36;
            const curtime = new Date().getTime();
            const issues = await github.rest.issues.listForRepo({
              repo: context.repo.repo,
              state: 'open',
              per_page: 100,
              page: 1
            });
            for (const issue of issues.data.values()) {
              console.log(issue.number);
            }
            
      - name: Display number of issues found
        run: |
          echo "Number of issues found: ${{ steps.get_issues.outputs.data.length }}"

#for (const issue of issues.data.values()) {
#  count = count + 1;
#}
