name: Button
on:
  workflow_dispatch:
  
jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get all open issues with label "RELEASE_NOTE"
        id: get_issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PGH_TOKEN }}
          script: |
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              repo: context.repo.repo,
              state: 'open',
              labels: 'RELEASE_NOTE'
            });
            const issues = await github.paginate(opts)
            core.setOutput('data', issues);
            
      - name: Display number of issues found
        run: |
          echo "Number of issues found: ${{ steps.get_issues.outputs.data.length }}"
