name: Button3
on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

jobs:
  do-job:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Send notification of deployment
      with:
        shell: bash
      run: |
        response="$(curl --location 'https://api.github.com/repos/${{ github.repository }}/issues' \
        --header 'Authorization: Bearer ${{ secrets.PGH_TOKEN }}' \
        --header 'Content-Type: text/plain' \
        --data '{
          "title": "CORE_DEV - BCentral deployment",
          "body": "**v1.0.1090.0** of BCentral was successfully deployed 🚀 on your SaaS envirronments. Please have a look at the new feature implemented ASAP. Envjoy",
          "assignees":["gillesbandza-pr"]
        }')"
