name: Button
on:
  workflow_dispatch:
  
jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get all open issues with label "RELEASE_NOTE"
        id: get_issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PGH_TOKEN }}
          script: |
            count = 0;
            const issues = await github.rest.issues.listForRepo.endpoint.merge({
              repo: context.repo.repo,
              state: 'open',
              labels: ['RELEASE_NOTE']
            });
            console.log(issues);
            console.log(issues.data);
            #for (const issue of issues.data.values()) {
            #  count = count + 1;
            #}
      - name: Display number of issues found
        run: |
          echo "Number of issues found: ${{ steps.get_issues.outputs.data.length }}"
