name: Button
on:
  workflow_dispatch:
  
jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get all open issues with label "RELEASE_NOTE"
        id: get_issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PGH_TOKEN }}
          script: |
            count = 0;
            
            issues = await github.issues.list({
              owner: context.repo.owner,
              repo: context.repo.name,
              labels: ["RELEASE_NOTE"]
            })
            for (const issue of issues) {
              console.log(issue.number)
            }
            
      - name: Display number of issues found
        run: |
          echo "Number of issues found: ${{ steps.get_issues.outputs.data.length }}"

#for (const issue of issues.data.values()) {
#  count = count + 1;
#}
