name: Button
on:
  workflow_dispatch:
  
jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
    - name: Mettre à jour le corps de la release
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: 125555777,
            body: "fdsdfsdfsdfds",
          });



