name: Button
on:
  workflow_dispatch:
  
jobs:
  do-job:
    runs-on: ubuntu-latest
    steps:
    - name: Update release
      uses: johnwbyrd/update-release@v1
      with:
        token: ${{ secrets.PGH_TOKEN }}
        body: "Wouhouuuuu"



