name: Mon Workflow

on:
  workflow_dispatch:
    inputs:
      choix:
        type: choice
        description: 'Choisissez une valeur : linux, cordova, apple, windows, home, town, all of them'
        options:
          - linux
          - cordova
          - apple
          - windows
          - home
          - town
          - all of them
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher le message
        run: echo "Hello, world!"

  run:
    needs: prepare
    strategy:
      matrix:
        item: ${{ github.repository == 'all of them' && [ a, b, c ] || [d, e] }}
    runs-on: ubuntu-latest
    steps:
      - name: Afficher l'item de la matrice
        run: echo "Item de la matrice :"
